### PR TITLE
fix missing reference rewrites in custom resource tmpl DependsOn

### PR DESCRIPTION
**Pull request by tavisrudd**
@dannosaur See if this fixes the issue you found.

### CODE REVIEW

**Comment by dannosaur** [comment]
If `DependsOn` is a single string, it's rewritten correctly..

**Input**

```
  IPv6Block:
    Type: AWS::EC2::VPCCidrBlock

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6Block
```

**Output**

```
  VPCIPv6Block:
    Type: 'AWS::EC2::VPCCidrBlock'
  VPCPublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    DependsOn: VPCIPv6Block
```

If it's a list of strings however;

**Input**

```
  IPv6Block:
    Type: AWS::EC2::VPCCidrBlock

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn:
      - IPv6Block
```

the following error is thrown;

```
TypeError: ref.trim is not a function
    at Visitor.maybeRewriteRef (/home/dan/workspace/iidy/lib/preprocess/visitor.js:394:39)
    at _.fromPairs._.map (/home/dan/workspace/iidy/lib/preprocess/visitor.js:625:43)
    at arrayMap (/home/dan/workspace/iidy/node_modules/lodash/lodash.js:639:23)
    at Function.map (/home/dan/workspace/iidy/node_modules/lodash/lodash.js:9554:14)
    at Visitor._visitResourceNode (/home/dan/workspace/iidy/lib/preprocess/visitor.js:623:11)
    at Visitor.visitResourceNode (/home/dan/workspace/iidy/lib/preprocess/visitor.js:618:21)
    at result (/home/dan/workspace/iidy/lib/preprocess/visitor.js:472:29)
    at Visitor.visitNode (/home/dan/workspace/iidy/lib/preprocess/visitor.js:496:11)
    at Visitor.visitCustomResource (/home/dan/workspace/iidy/lib/preprocess/visitor.js:675:38)
    at _.fromPairs._.map (/home/dan/workspace/iidy/lib/preprocess/visitor.js:628:29)
    at arrayMap (/home/dan/workspace/iidy/node_modules/lodash/lodash.js:639:23)
    at Function.map (/home/dan/workspace/iidy/node_modules/lodash/lodash.js:9554:14)
    at Visitor._visitResourceNode (/home/dan/workspace/iidy/lib/preprocess/visitor.js:623:11)
    at Visitor.visitResourceNode (/home/dan/workspace/iidy/lib/preprocess/visitor.js:618:21)
    at result (/home/dan/workspace/iidy/lib/preprocess/visitor.js:472:29)
    at Visitor.visitNode (/home/dan/workspace/iidy/lib/preprocess/visitor.js:496:11)
```

**Comment by tavisrudd** [comment]
Ah, I missed a case. You want to practice your typescript again and add support for that to this branch?

**Comment by dannosaur** [comment]
I think I got it ;)

Seems to now work in both situations where `DependsOn` is either a string or an array.

I also spotted that `Condition` wasn't handled either, so I added the same for that. The CFN spec says that `Condition` can only be a string, so there was no point handling the input being an array as that'd be an invalid template.

**Input**

```
Conditions:
  MyCondition: true

Resources:
  VPC:
    $global: true
    Type: AWS::EC2::VPC
  IPv6Block:
    Type: AWS::EC2::VPCCidrBlock
  PublicSubnet1:
    $global: true
    Type: AWS::EC2::Subnet
    DependsOn:
      - IPv6Block
  PublicSubnet2:
    $global: true
    Type: AWS::EC2::Subnet
    DependsOn: IPv6Block
    Condition: MyCondition
```

**Output**

```
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
  VPCIPv6Block:
    Type: 'AWS::EC2::VPCCidrBlock'
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    DependsOn:
      - VPCIPv6Block
  PublicSubnet2:
    Type: 'AWS::EC2::Subnet'
    DependsOn: VPCIPv6Block
    Condition: MyCondition
Conditions:
  VPCMyCondition: true
```

I started to write tests to cover it, however it seems I need to learn a bit more about how templates are parsed out and rendered internally as, while I can get the test to rewrite the DependsOn/Condition value(s), I can't get it to rewrite the resource names themselves to match up with the expected template.

**Comment by tavisrudd** [comment]
LGTM. Thanks.

**Pull request merged**
